
# Constants
SCREEN_WIDTH = 160
SCREEN_HEIGHT = 120
BLOCK_SIZE = 8
SPRITE_BANK_GAME = 0
SPRITE_BANK_UI = 1

SPRITE_SELECT_NORMAL = (SPRITE_BANK_GAME, 0, 0, 8, 8, 0)
SPRITE_SELECT_LARGE = (SPRITE_BANK_GAME, 0, 8, 10, 10, 0)
SPRITE_CURSOR = (SPRITE_BANK_GAME, 16, 0, 8, 8, 0)

SPRITE_BLOCK_ERROR = (SPRITE_BANK_UI, 8, 0, 8, 8, 1)
SPRITE_BLOCK_DIRT = (SPRITE_BANK_UI, 8, 0, 8, 8, 0)
SPRITE_BLOCK_GRASS = (SPRITE_BANK_UI, 16, 0, 8, 8, 0)
SPRITE_BLOCK_STONE = (SPRITE_BANK_UI, 8, 8, 8, 8, 0)
SPRITE_BLOCK_COAL = (SPRITE_BANK_UI, 16, 8, 8, 8, 1)

SPRITE_BREAK_ANIM_BANK = SPRITE_BANK_UI
SPRITE_BREAK_ANIM_U = 0
SPRITE_BREAK_ANIM_V_START = 0
SPRITE_BREAK_ANIM_COLKEY = 11

COLOR_BUTTON_BG = 13
COLOR_BUTTON_BORDER = 7
COLOR_BUTTON_TEXT = 7
COLOR_BUTTON_PRESSED_BG = 10
COLOR_BUTTON_PRESSED_TEXT = 7

MENU_ITEM_HEIGHT = 10
MENU_PADDING = 5
CHECKBOX_SIZE = 7
CHECKBOX_TEXT_GAP = 3
DROPDOWN_ARROW_WIDTH = 8
DROPDOWN_ARROW_HEIGHT = 5

SAVE_FILE_NAME = "savegame.json"

LANG_FOLDER = "lang"
DEFAULT_LANGUAGE = "en_us"
FONT_SIZE = 8

NOTIFICATION_PADDING_X = 5
NOTIFICATION_PADDING_Y = 3
NOTIFICATION_LINE_SPACING = 2
NOTIFICATION_INTER_ITEM_SPACING = 2
NOTIFICATION_MAX_WIDTH = 115
NOTIFICATION_MAX_DISPLAY_TIME = 2
MAX_NOTIFICATIONS = 3

NOTIFICATION_FADE_IN_AMOUNT_Y_PER_FRAME = 5
NOTIFICATION_FADE_OUT_INITIAL_AMOUNT_X_PER_FRAME = 2
NOTIFICATION_FADE_OUT_ACCELERATION_X_PER_FRAME = 0.5
NOTIFICATION_FADE_IN_OFFSET_Y = -30
NOTIFICATION_TARGET_Y_TOLERANCE = 1

NOTIFICATION_BG_COLOR = 13
NOTIFICATION_TEXT_COLOR_INFO = 0
NOTIFICATION_TEXT_COLOR_ERROR = 8
NOTIFICATION_TEXT_COLOR_SUCCESS = 5

CHUNK_SIZE_X_BLOCKS = 16
CHUNK_SIZE_Y_BLOCKS = 16

SPRITE_ID_MAP = {
    "air": None,
    "dirt": SPRITE_BLOCK_DIRT,
    "grass": SPRITE_BLOCK_GRASS,
    "stone": SPRITE_BLOCK_STONE,
    "coal": SPRITE_BLOCK_COAL,
}
ID_SPRITE_MAP = {v_str: k_tuple for k_tuple, v_str in SPRITE_ID_MAP.items() if isinstance(k_tuple, str)}
for k_str, v_tuple in SPRITE_ID_MAP.items():
    if isinstance(v_tuple, tuple):
        ID_SPRITE_MAP[k_str] = v_tuple
    elif v_tuple is None and k_str == "air":
        ID_SPRITE_MAP[k_str] = None
