pub enum GameEvent {
    OpenSaveSelection,
    LoadSave(String),
    StartNewGameSetup,
    ConfirmNewGame(String),
    SaveGame,
    QuitGame,
    ReturnToTitle,
    ReturnToTitleFromSaveSelect,
    UpgradeDrill,
    UpgradeTank,
    UpgradeEngine,
    UpgradeCargo,
    BuyWarpGate,
    StartPlaceWarpGate,
    ConfirmWarpGateName(String),
    OpenWarpMenu,
    TeleportToWarp(usize),
    CloseMenu,
    OpenShop,
    OpenWarehouse,
    SellItem(String, usize),
    DepositItem(String, usize),
    WithdrawItem(String, usize),
}
